# Site settings
title: Julia Ebert
author: Julia Ebert
email: julia@juliaebert.com
description: > # this means to ignore newlines until "baseurl:"
  I am a bioengineering student and programmer interested in
  human motor learning, robotics, and the interface between the two,
  such as robotic prosthetics, biomimetic robotics, and artificial intelligence.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juliaebert.com" # the base hostname & protocol for your site
twitter_username: jtebert
github_username:  jtebert

google_analytics: UA-54476418-1

# Build settings
markdown: kramdown
